---
anchors:
  entity_button_mobile: &entitybuttonmobile
    style: |
      :host {
        border-radius: 22px;
        -webkit-box-shadow: 5px 5px 5px 0px #1a1a1a, inset 4px 4px 15px 0px #1a1a1a, 5px 5px 15px 5px rgba(0,0,0,0); 
        box-shadow: 5px 5px 5px 0px #1a1a1a, inset 4px 4px 15px 0px #1a1a1a, 5px 5px 15px 5px rgba(0,0,0,0);
        --paper-card-background-color: rgba(0,0,0,0.36);
        --paper-item-icon-active-color: var(--sidebar-icon-color);
        --paper-item-icon-color: var(--darker-grey-color);
        font-size: .5em;
        padding 1px;
      }

 # input_boolean.mobile_kiosk
title: ' '
style:
  background: url("/local/images-lovelace/backgroundz/greydark.jpg")
  background-repeat: no-repeat
  background-size: 100% 100%
  padding: 8px 0px 0px 0px
  border-radius: 22px
  border: 'solid 3px var(--accent-color-lighter)'
  "--primary-text-color": rgba(255,255,255,0.80)
  "--iron-icon-height": 35px
  "--iron-icon-width": 35px
  "--app-toolbar-font-size": 2.3em
  text-shadow: "2px 2px 4px #000000"
  font-size: 1.1em
  text-transform: capitalize
  font-variant: small-caps
  width: calc(100% - 10px)
  height: calc(100% - 6px)
  box-sizing: border-box
  margin: 0
card:
  type: custom:mod-card
  style: |
    ha-card {
      font-size: .65em;
      --paper-card-background-color: rgba(0, 0, 0,0.85);
      padding: 2px 15px 2px 10px;
    )
  card:
    type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: button
            entity: input_boolean.notifications
            <<: *entitybuttonmobile
            name: Notifications
            tap_action:
              action: toggle
          - type: button
            entity: input_boolean.voice_notifications
            <<: *entitybuttonmobile
            name: Voice Alerts
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: button
            entity: input_boolean.garage_entry_voice
            <<: *entitybuttonmobile
            name: Garage Entry Alert
            tap_action:
              action: toggle
          - type: button
            entity: input_boolean.disable_auto_garage
            <<: *entitybuttonmobile
            name: Disable Auto OHD
            icon: mdi:garage-alert-variant
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: button
            entity: input_boolean.disable_garage_auto_lights
            <<: *entitybuttonmobile
            name: Disable Auto Garage
            icon: mdi:lightbulb-group-off
            tap_action:
              action: toggle
          - type: button
            entity: input_boolean.disable_patio_motion
            <<: *entitybuttonmobile
            name: Disable Patio Motion
            icon: mdi:motion-sensor
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: button
            entity: input_boolean.disable_auto_bedroom
            <<: *entitybuttonmobile
            name: Disable Auto Master
            icon: mdi:lightbulb-group-off
            tap_action:
              action: toggle
          - type: button
            entity: input_boolean.disable_auto_bathroom
            <<: *entitybuttonmobile
            name: Disable Auto Bath
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: button
            entity: input_boolean.disable_auto_fans
            <<: *entitybuttonmobile
            name: Disable Auto Fans
            tap_action:
              action: toggle
          - type: button
            entity: input_boolean.disable_exterior_auto_lights
            <<: *entitybuttonmobile
            name: Disable Exterior
            icon: mdi:lightbulb-group-off
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: button
            entity: input_boolean.disable_mail_notifications
            <<: *entitybuttonmobile
            name: Disable Mail
            icon: mdi:mailbox-open
            tap_action:
              action: toggle
          - type: button
            entity: input_boolean.disable_laundry_notifications
            <<: *entitybuttonmobile
            name: Disable Laundry
            icon: mdi:account-tie-voice
            tap_action:
              action: toggle
