# /config/includes/sensor.yaml
####################################################
- platform: min_max
  entity_ids:
    - sensor.office_temp
    - sensor.office_smoke_temp
  name: office_temp_avg
  type: mean
- platform: min_max
  entity_ids:
#    - sensor.living_room_thermostat_temperature
    - sensor.laundry_smoke_temp
    - sensor.office_temp
    - sensor.office_smoke_temp
    - sensor.bedroom_temp
    - sensor.kitchen_temp
    - sensor.mbath_temp
    - sensor.spare_room_temp
    - sensor.laundry_room_temp
  name: realistic_temperature
  type: mean
- platform: filter
  name: "Filtered Realistic Temperature"
  entity_id: sensor.realistic_temperature
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: lowpass
      time_constant: 10
    - filter: time_simple_moving_average
      window_size: 00:05
      precision: 2
- platform: min_max
  entity_ids:
    - sensor.office_humidity
    - sensor.bedroom_humidity
#    - sensor.living_room_thermostat_humidity
    - sensor.kitchen_humidity
    - sensor.mbath_humidity
    - sensor.spare_room_humidity
    - sensor.laundry_room_humidity
  name: realistic_humidity
  type: mean
- platform: filter
  name: "Filtered Realistic Humidity"
  entity_id: sensor.realistic_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2
# Current Time and Date
- platform: time_date
  display_options:
    - 'time'
    - 'date'
# HA latest version
- platform: rest
  name: "HA Latest Version"
  resource: https://pypi.python.org/pypi/homeassistant/json
  value_template: '{{ value_json.info.version }}'
  scan_interval: 3600
##  GitHub
#- platform: github
#  access_token: !secret github_token
#  repositories:
#    - path: 'Dino-Tech/Home-Assistant-Config'  #'Dino-Tech/Home-Assistant-Config'

# Google Wifi
- platform: google_wifi
#
- platform: template
  sensors:
    day_night:
      friendly_name: "Day/Night"
      value_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          Day
        {% else %}
          Night
        {% endif %}
      entity_picture_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          /local/images-lovelace/sun.jpg
        {% else %}
          /local/images-lovelace/night.jpg
        {% endif %}

- platform: template
  sensors:
    dark_sky_current_text:
      value_template: '{% if is_state("sensor.dark_sky_icon","clear-day") %} Clear 
                       {% elif is_state("sensor.dark_sky_icon","clear-night") %} Clear 
                       {% elif is_state("sensor.dark_sky_icon","rain") %} Rain
                       {% elif is_state("sensor.dark_sky_icon","snow") %} Snowy
                       {% elif is_state("sensor.dark_sky_icon","fog") %} Foggy
                       {% elif is_state("sensor.dark_sky_icon","sleet") %} Sleet
                       {% elif is_state("sensor.dark_sky_icon","wind") %} Windy
                       {% elif is_state("sensor.dark_sky_icon","cloudy") %} Cloudy
                       {% elif is_state("sensor.dark_sky_icon","partly-cloudy-day") %} Partly Cloudy
                       {% elif is_state("sensor.dark_sky_icon","partly-cloudy-night") %} Partly Cloudy
                       {% elif is_state("sensor.dark_sky_icon","hail") %} Hailing
                       {% elif is_state("sensor.dark_sky_icon","lightning") %} Lightning
                       {% elif is_state("sensor.dark_sky_icon","thunderstorm") %} Thunderstorm
                       {% endif %}'

- platform: template
  sensors:

    pixel2statusbatt:
      value_template: '{% if states.device_tracker.google_maps_105311213674095510695 %} {{ states.device_tracker.google_maps_105311213674095510695.attributes.battery_level |int }} {% else %} Unknown {% endif %}'
      unit_of_measurement: '%'

    sunset:
      value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M") %} {{ timestamp.lstrip("0") }}'
      unit_of_measurement: 'PM'

    sunrise:
      value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M") %} {{ timestamp.lstrip("0") }}'
      unit_of_measurement: 'AM'

    daylight:
      value_template: >
        {% set nr = as_timestamp(state_attr('sun.sun','next_rising')) %}
        {% set ns = as_timestamp(state_attr('sun.sun','next_setting')) %}
        {% if nr > ns %}
          {% set nr = nr - 60*60*24 %}
        {% endif %}
        {{ (ns - nr)|timestamp_custom('%H:%M',false) }}

#Thanks to @ccostan for the code here.  Some Intresting HA stats
    sensor_count:
      entity_id: []
      friendly_name: 'Number of Sensors'
      value_template: >
        {%- set domains = ['sensor'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}

    automation_count:
      entity_id: []
      friendly_name: 'Number of Automations'
      value_template: >
        {%- set domains = ['automation'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}

    script_count:
      entity_id: []
      friendly_name: 'Number of Scripts'
      value_template: >
        {%- set domains = ['script'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}

    switch_count:
      entity_id: []
      friendly_name: 'Number of Switches'
      value_template: >
        {%- set domains = ['switch'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}

    binary_sensor_count:
      entity_id: []
      friendly_name: 'Number of Binary Sensors'
      value_template: >
        {%- set domains = ['binary_sensor'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}

    lights_count:
      entity_id: []
      friendly_name: 'Number of Lights'
      value_template: >
        {%- set domains = ['light'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}

    tracker_count:
      entity_id: []
      friendly_name: 'Number of Devices'
      value_template: >
        {%- set domains = ['device_tracker'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}


- platform: mqtt
  name: "zdummy sensor 1"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 2"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 3"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 4"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 5"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 6"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 7"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 8"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 9"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 10"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 11"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 12"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 13"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 14"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 15"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 16"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 17"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 18"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 19"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 20"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 21"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 22"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 23"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 24"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 25"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 26"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 27"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 28"
  state_topic: "zdummy/state/one"
- platform: mqtt
  name: "zdummy sensor 29"
  state_topic: "zdummy/state/one"

- platform: mqtt
  name: "Washer State"
  state_topic: "hass/state/washer"
  icon: mdi:washing-machine
- platform: mqtt
  name: "Washer Watts"
  state_topic: "tele/SNF-Washer/SENSOR"
  value_template: "{{value_json['ENERGY'].Power }}"
  qos: 2
  unit_of_measurement : "W"
  icon: mdi:flash-outline
  availability_topic: "tele/SNF-Washer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Washer Voltage"
  state_topic: "tele/SNF-Washer/SENSOR"
  value_template: "{{value_json['ENERGY'].Voltage }}"
  qos: 2
  unit_of_measurement : "V"
  icon: mdi:flash-circle
  availability_topic: "tele/SNF-Washer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Washer Amps"
  state_topic: "tele/SNF-Washer/SENSOR"
  value_template: "{{value_json['ENERGY'].Current }}"
  qos: 2
  unit_of_measurement : "A"
  icon: mdi:flash
  availability_topic: "tele/SNF-Washer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Washer Energy Today"
  icon: mdi:google-analytics
  state_topic: "tele/SNF-Washer/SENSOR"
  value_template: "{{value_json['ENERGY'].Today }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/SNF-Washer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Washer Energy Yesterday"
  icon: mdi:chart-line-stacked
  state_topic: "tele/SNF-Washer/SENSOR"
  value_template: "{{value_json['ENERGY'].Yesterday }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/SNF-Washer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  state_topic: "tele/SNF-Washer/STATE"
  name: "Washer Signal"
  icon: mdi:rss
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/SNF-Washer/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Dryer State"
  state_topic: "hass/state/dryer"
  icon: mdi:washing-machine
- platform: mqtt
  name: "Dryer Watts"
  state_topic: "tele/SNF-Dryer/SENSOR"
  value_template: "{{value_json['ENERGY'].Power }}"
  qos: 2
  unit_of_measurement : "W"
  icon: mdi:flash-outline
  availability_topic: "tele/SNF-Dryer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Dryer Voltage"
  state_topic: "tele/SNF-Dryer/SENSOR"
  value_template: "{{value_json['ENERGY'].Voltage }}"
  qos: 2
  unit_of_measurement : "V"
  icon: mdi:flash-circle
  availability_topic: "tele/SNF-Dryer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Dryer Amps"
  state_topic: "tele/SNF-Dryer/SENSOR"
  value_template: "{{value_json['ENERGY'].Current }}"
  qos: 2
  unit_of_measurement : "A"
  icon: mdi:flash
  availability_topic: "tele/SNF-Dryer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Dryer Energy Today"
  icon: mdi:google-analytics
  state_topic: "tele/SNF-Dryer/SENSOR"
  value_template: "{{value_json['ENERGY'].Today }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/SNF-Dryer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Dryer Energy Yesterday"
  icon: mdi:chart-line-stacked
  state_topic: "tele/SNF-Dryer/SENSOR"
  value_template: "{{value_json['ENERGY'].Yesterday }}"
  qos: 2
  unit_of_measurement : "kWh"
  availability_topic: "tele/SNF-Dryer/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  state_topic: "tele/SNF-Dryer/STATE"
  name: "Dryer Signal"
  icon: mdi:rss
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/SNF-Dryer/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  state_topic: "tele/sonoff40/STATE"
  name: "Mbath Signal"
  icon: mdi:rss
  unit_of_measurement: "%"
  value_template: "{{value_json['Wifi'].RSSI }}"
  availability_topic: "tele/sonoff40/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Mbath Temp"
  state_topic: "tele/sonoff40/SENSOR"
  value_template: "{{value_json['AM2301'].Temperature }}"
  qos: 1
  unit_of_measurement: "°F"
  availability_topic: "tele/sonoff40/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Mbath Humidity"
  state_topic: "tele/sonoff40/SENSOR"
  value_template: "{{value_json['AM2301'].Humidity }}"
  qos: 1
  unit_of_measurement: "%"
  device_class: humidity
  availability_topic: "tele/sonoff40/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Kitchen Temp"
  state_topic: "tele/sonoff09/SENSOR"
  value_template: "{{value_json['AM2301'].Temperature }}"
  qos: 1
  unit_of_measurement: "°F"
  availability_topic: "tele/sonoff09/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Kitchen Humidity"
  state_topic: "tele/sonoff09/SENSOR"
  value_template: "{{value_json['AM2301'].Humidity }}"
  qos: 1
  unit_of_measurement: "%"
  device_class: humidity
  availability_topic: "tele/sonoff09/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Office Temp"
  state_topic: "tele/sonoffT302/SENSOR"
  value_template: "{{value_json['AM2301'].Temperature }}"
  qos: 1
  unit_of_measurement: "°F"
  availability_topic: "tele/sonoffT302/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Office Humidity"
  state_topic: "tele/sonoffT302/SENSOR"
  value_template: "{{value_json['AM2301'].Humidity }}"
  qos: 1
  unit_of_measurement: "%"
  device_class: humidity
  availability_topic: "tele/sonoffT302/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bedroom Temp"
  state_topic: "tele/sonoffKLD-034/SENSOR"
  value_template: "{{value_json['AM2301'].Temperature }}"
  qos: 1
  unit_of_measurement: "°F"
  availability_topic: "tele/sonoffKLD-034/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bedroom Humidity"
  state_topic: "tele/sonoffKLD-034/SENSOR"
  value_template: "{{value_json['AM2301'].Humidity }}"
  qos: 1
  unit_of_measurement: "%"
  device_class: humidity
  availability_topic: "tele/sonoffKLD-034/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
####################
- platform: mqtt
  state_topic: "shellies/shellyht-58FD2A/sensor/temperature"
  name: "Laundry Room Temp"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellyht-58FD2A/sensor/battery"
  name: "Laundry Room Battery"
  icon: mdi:battery-charging-80
  unit_of_measurement: "%"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellyht-58FD2A/sensor/humidity"
  name: "Laundry Room Humidity"
  icon: mdi:water
  unit_of_measurement: "%"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellyht-5A8B31/sensor/temperature"
  name: "Outside HT Temp"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellyht-5A8B31/sensor/battery"
  name: "Outside HT Battery"
  icon: mdi:battery-charging-80
  unit_of_measurement: "%"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellyht-5A8B31/sensor/humidity"
  name: "Outside HT Humidity"
  icon: mdi:water
  unit_of_measurement: "%"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellyht-5A8AFC/sensor/temperature"
  name: "Spare Room Temp"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellyht-5A8AFC/sensor/battery"
  name: "Spare Room Battery"
  icon: mdi:battery-charging-80
  unit_of_measurement: "%"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellyht-5A8AFC/sensor/humidity"
  name: "Spare Room Humidity"
  icon: mdi:water
  unit_of_measurement: "%"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellysmoke-5B899E/sensor/temperature"
  name: "Laundry Smoke Temp"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellysmoke-5B899E/sensor/battery"
  name: "Laundry Smoke Battery"
  icon: mdi:battery-charging-80
  unit_of_measurement: "%"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellysmoke-5B897C/sensor/temperature"
  name: "Office Smoke Temp"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellysmoke-5B897C/sensor/battery"
  name: "Office Smoke Battery"
  icon: mdi:battery-charging-80
  unit_of_measurement: "%"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellysmoke-5B898B/sensor/temperature"
  name: "Garage Smoke Temp"
  icon: mdi:thermometer
  unit_of_measurement: "°F"
  qos: 2
####################
- platform: mqtt
  state_topic: "shellies/shellysmoke-5B898B/sensor/battery"
  name: "Garage Smoke Battery"
  icon: mdi:battery-charging-80
  unit_of_measurement: "%"
  qos: 2

# Uptime Sensor
- platform: uptime

- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: memory_use_percent
    - type: load_1m

- platform: template
  sensors:
    door_count:
      entity_id: sensor.door_count
      friendly_name: "Open Door Count"
      value_template: >-
        {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'door') | list | count | int }}

- platform: template
  sensors:
    window_count:
      entity_id: sensor.window_count
      friendly_name: "Open Window Count"
      value_template: >-
        {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'window') | list | count | int }}


####################
#- platform: plex
#  name: New Life Media
#  host: 192.168.1.78
#  port: 32400
#  ssl: false
#  username: Darren_W
#  password: doNNa2017!@#
#  server: New Life Media
