## weather#includes /config/packages/weather.yaml
#################################################################
homeassistant:
  customize:
    sensor.moon:
      icon: mdi:weather-night
    sensor.dark_sky_apparent_temperature:
      icon: mdi:thermometer
group:
  weather:
    name: Weather
    control: hidden
    entities:
      - sensor.day_night
      - sensor.moon
      - sensor.dark_sky_moon_phase
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daytime_high_temperature_0d
      - sensor.dark_sky_overnight_low_temperature_0d
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_type
      - sensor.dark_sky_humidity
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_pressure
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_visibility
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_nearest_storm_bearing
  weather_summary:
    name: Weather Summary
    control: hidden
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary 
  weather_forecast:
    name: Weather Forecast
    control: hidden
    entities:
      - weather.covington_forecast

sensor:
  - platform: moon

# Dark Sky Weather
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
      - dew_point # added
      - minutely_summary # added
      - hourly_summary # added
      - moon_phase # added
    scan_interval:
      minutes: 6

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api
    name: Covington Forecast
  - platform: darksky
    api_key: !secret darksky_api