---
# # binary sensor#  /config/includes/binary_sensor.yaml
# ######################################################
- platform: wyzesense
  device: auto

- platform: workday
  country: US

- platform: mqtt
  name: "Guest Smoke Detected"
  state_topic: "shellies/shellysmoke-743B47/sensor/smoke"
  qos: 2
  payload_on: 'true'
  payload_off: 'false'
  device_class: smoke

- platform: mqtt
  name: "Bedroom Smoke Detected"
  state_topic: "shellies/shellysmoke-743B24/sensor/smoke"
  qos: 2
  payload_on: 'true'
  payload_off: 'false'
  device_class: smoke

- platform: mqtt
  name: "Garage Smoke Detected"
  state_topic: "shellies/shellysmoke-5B898B/sensor/smoke"
  qos: 2
  payload_on: 'true'
  payload_off: 'false'
  device_class: smoke

- platform: mqtt
  name: "Laundry Smoke Detected"
  state_topic: "shellies/shellysmoke-5B899E/sensor/smoke"
  qos: 2
  payload_on: 'true'
  payload_off: 'false'
  device_class: smoke

- platform: mqtt
  state_topic: "shellies/shellysmoke-5B897C/sensor/smoke"
  name: "Office Smoke Detected"
  qos: 2
  payload_on: 'true'
  payload_off: 'false'
  device_class: smoke

- platform: mqtt
  name: "Water Heater"
  state_topic: "RFBridge/water1"
  availability_topic: "tele/RF_Bridge/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: moisture

- platform: mqtt
  name: "Washer Leak"
  state_topic: "RFBridge/water2"
  availability_topic: "tele/RF_Bridge/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: moisture

# - platform: mqtt
#   name: "Garage Door"
#   state_topic: "RFBridge/sensor1"
#   availability_topic: "tele/RF_Bridge/LWT"
#   qos: 1
#   payload_on: "Open"
#   payload_off: "Closed"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   device_class: garage_door

- platform: mqtt
  name: "Front Motion"
  state_topic: "RFBridge/motion1"
  availability_topic: "tele/RF_Bridge/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  name: "Driveway Motion"
  state_topic: "RFBridge/motion2"
  availability_topic: "tele/RF_Bridge/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

# - platform: mqtt
#   name: "Entry Hall Motion"
#   state_topic: "RFBridge/motion3"
#   availability_topic: "tele/RF_Bridge/LWT"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   device_class: motion

- platform: mqtt
  name: "Back Motion"
  state_topic: "RFBridge/motion4"
  availability_topic: "tele/RF_Bridge/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  name: "Garage Motion"
  state_topic: "RFBridge/motion5"
  availability_topic: "tele/RF_Bridge/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  name: "Hallway RF Motion"
  state_topic: "RFBridge/motion6"
  availability_topic: "tele/RF_Bridge/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  name: "Bedroom Motion"
  state_topic: "Bedroom/PIR/state"
  availability_topic: "tele/sonoffKLD-034/LWT"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  name: "Hallway Motion"
  state_topic: "Hallway/PIR/state"
  availability_topic: "tele/sonoff39/LWT"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  name: "MBath Motion"
  state_topic: "MBath/PIR/state"
  availability_topic: "tele/sonoff40/LWT"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  name: "Hall Motion"
  state_topic: "Hall/PIR/state"
  availability_topic: "tele/sonoff39/LWT"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  name: "Den Motion"
  state_topic: "Den/PIR/state"
  availability_topic: "tele/sonoff39/LWT"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/motion"
  name: "Motion"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/face"
  name: "Face Detected"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion

# alert tmeplate sensors
- platform: template
  sensors:
    office_smoke_battery_low:
      value_template: '{{ states("sensor.office_smoke_battery")|float < 35 }}'
      friendly_name: 'Office smoke battery is low'

- platform: template
  sensors:
    guest_smoke_battery_low:
      value_template: '{{ states("sensor.guest_smoke_battery")|float < 35 }}'
      friendly_name: 'Guest smoke battery is low'

- platform: template
  sensors:
    badroom_smoke_battery_low:
      value_template: '{{ states("sensor.bedroom_smoke_battery")|float < 35 }}'
      friendly_name: 'Bedroom smoke battery is low'

- platform: template
  sensors:
    laundry_smoke_battery_low:
      value_template: '{{ states("sensor.laundry_smoke_battery")|float < 35 }}'
      friendly_name: 'Laundry smoke battery is low'

- platform: template
  sensors:
    garage_smoke_battery_low:
      value_template: '{{ states("sensor.garage_smoke_battery")|float < 35 }}'
      friendly_name: 'Garage smoke battery is low'

- platform: template
  sensors:
    patio_ht_battery_low:
      value_template: '{{ states("sensor.patio_ht_battery")|float < 35 }}'
      friendly_name: 'Patio HT battery is low'

- platform: template
  sensors:
    porch_ht_battery_low:
      value_template: '{{ states("sensor.porch_ht_battery")|float < 35 }}'
      friendly_name: 'Porch HT battery is low'

- platform: template
  sensors:
    guest_ht_battery_low:
      value_template: '{{ states("sensor.spare_room_battery")|float < 35 }}'
      friendly_name: 'Guest HT battery is low'

- platform: template
  sensors:
    laundry_ht_battery_low:
      value_template: '{{ states("sensor.laundry_room_battery")|float < 35 }}'
      friendly_name: 'Laundry HT battery is low'

- platform: template
  sensors:
    bathroom_ht_battery_low:
      value_template: '{{ states("sensor.bathroom_ht_battery")|float < 35 }}'
      friendly_name: 'Bathroom HT battery is low'

- platform: template
  sensors:
    ensuite_ht_battery_low:
      value_template: '{{ states("sensor.ensuite_ht_battery")|float < 35 }}'
      friendly_name: 'Ensuite HT battery is low'

- platform: template
  sensors:
    pixel_2_xl_battery_low:
      value_template: '{{ states.device_tracker.life360_darren_wilson.attributes.battery < 25 }}'
      friendly_name: 'Pixel 2 XL battery is low'

- platform: template
  sensors:
    iphone_6_battery_low:
      value_template: '{{ states.device_tracker.life360_donna_wilson.attributes.battery < 25 }}'
      friendly_name: 'iPhone 6 battery is low'

- platform: template
  sensors:
    hacs_update_available:
      value_template: '{{ states("sensor.hacs")|float > 0 }}'
      friendly_name: 'HACS update(s) available'

- platform: template
  sensors:
    front_door_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_7780f0b4.attributes.battery_level < 35 }}'
      friendly_name: 'Front door sensor battery is low'

- platform: template
  sensors:
    garage_door_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_7780f0c5.attributes.battery_level < 35 }}'
      friendly_name: 'Garage door sensor battery is low'

- platform: template
  sensors:
    laundry_motion_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_778168e9.attributes.battery_level < 35 }}'
      friendly_name: 'Laundry motion battery is low'

- platform: template
  sensors:
    entry_hall_motion_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_778797dc.attributes.battery_level < 35 }}'
      friendly_name: 'Entry Hall motion battery is low'

- platform: template
  sensors:
    hall_bath_motion_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_77802215.attributes.battery_level < 35 }}'
      friendly_name: 'Hall Bath motion battery is low'

- platform: template
  sensors:
    porch_motion_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_77878ecb.attributes.battery_level < 35 }}'
      friendly_name: 'Porch motion battery is low'

- platform: template
  sensors:
    porch_motion_2_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_77933be2.attributes.battery_level < 35 }}'
      friendly_name: 'Porch motion 2 battery is low'

- platform: template
  sensors:
    garage_motion_1_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_77879826.attributes.battery_level < 35 }}'
      friendly_name: 'Garage motion 1 battery is low'

- platform: template
  sensors:
    garage_motion_2_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_77879025.attributes.battery_level < 35 }}'
      friendly_name: 'Garage motion 2 battery is low'

- platform: template
  sensors:
    garage_motion_3_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_77879025.attributes.battery_level < 35 }}'
      friendly_name: 'Garage motion 3 battery is low'

- platform: template
  sensors:
    mailbox_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_7782a115.attributes.battery_level < 35 }}'
      friendly_name: 'Mailbox sensor battery is low'

- platform: template
  sensors:
    kitchen_motion_1_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_7787900d.attributes.battery_level < 35 }}'
      friendly_name: 'Kitchen motion 1 battery is low'

- platform: template
  sensors:
    kitchen_motion_2_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_77878a66.attributes.battery_level < 35 }}'
      friendly_name: 'Kitchen motion 2 battery is low'

- platform: template
  sensors:
    office_motion_1_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_77933ddc.attributes.battery_level < 35 }}'
      friendly_name: 'Office motion 1 battery is low'

- platform: template
  sensors:
    office_motion_2_battery_low:
      value_template: '{{ states.binary_sensor.wyzesense_7793f9df.attributes.battery_level < 35 }}'
      friendly_name: 'Office motion 2 battery is low'

- platform: template
  sensors:
    weather_alert_detected:
      value_template: '{{ states("sensor.st_tammany")|float > 0 }}'
      friendly_name: 'Weather alerts active'
