##      /config/includes/cover.yaml
#####################################################
##  cover:
- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_door', 'on') }}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_door
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_door
      icon_template: >-
        {% if is_state('binary_sensor.garage_door', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}