---
# #      /config/includes/cover.yaml
# ####################################################
# #  cover:
- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_door', 'on') }}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_door
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_door
      icon_template: >-
        {% if is_state('binary_sensor.garage_door', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}

- platform: template
  covers:
    door:
      friendly_name: "Lovelace Lock"
      value_template: "{{ is_state('input_boolean.lovelace_lock', 'on') }}"
      open_cover:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.lovelace_lock
      close_cover:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lovelace_lock
      icon_template: >-
        {% if is_state('input_boolean.lovelace_lock', 'on') %}
          mdi:television-clean
        {% else %}
          mdi:television-off
        {% endif %}
