---
# #  light# /config/includes/light.yaml
# ############################################################

- platform: !secret light_platform
  username: !secret light_username
  password: !secret light_password

- platform: mqtt
  name: "Bathtub Light"
  command_topic: "cmnd/tasmota13/POWER"
  state_topic: "tele/tasmota13/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/tasmota13/LWT"
  brightness_command_topic: "cmnd/tasmota13/Dimmer"
  brightness_state_topic: "tele/tasmota13/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  white_value_state_topic: "tele/tasmota13/STATE"
  white_value_command_topic: "cmnd/tasmota13/white"
  white_value_scale: 100
  white_value_template: "{{ value_json.Channel[3] }}"
  rgb_command_topic: "cmnd/tasmota13/Color2"
  rgb_state_topic: "tele/tasmota13/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/tasmota13/Scheme"
  effect_state_topic: "tele/tasmota13/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Donnas Light"
  command_topic: "cmnd/tasmota14/POWER"
  state_topic: "tele/tasmota14/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/tasmota14/LWT"
  brightness_command_topic: "cmnd/tasmota14/Dimmer"
  brightness_state_topic: "tele/tasmota14/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  white_value_state_topic: "tele/tasmota14/STATE"
  white_value_command_topic: "cmnd/tasmota14/white"
  white_value_scale: 100
  white_value_template: "{{ value_json.Channel[3] }}"
  rgb_command_topic: "cmnd/tasmota14/Color2"
  rgb_state_topic: "tele/tasmota14/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/tasmota14/Scheme"
  effect_state_topic: "tele/tasmota14/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Darrens Light"
  command_topic: "cmnd/tasmota12/POWER"
  state_topic: "tele/tasmota12/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/tasmota12/LWT"
  brightness_command_topic: "cmnd/tasmota12/Dimmer"
  brightness_state_topic: "tele/tasmota12/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  white_value_state_topic: "tele/tasmota12/STATE"
  white_value_command_topic: "cmnd/tasmota12/white"
  white_value_scale: 100
  white_value_template: "{{ value_json.Channel[3] }}"
  rgb_command_topic: "cmnd/tasmota12/Color2"
  rgb_state_topic: "tele/tasmota12/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/tasmota12/Scheme"
  effect_state_topic: "tele/tasmota12/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "OfficeDimmer"
  state_topic: "stat/OfficeDimmer/POWER"
  command_topic: "cmnd/OfficeDimmer/POWER"
  availability_topic: "tele/OfficeDimmer/LWT"
  brightness_state_topic: "stat/OfficeDimmer/RESULT"
  brightness_command_topic: "cmnd/OfficeDimmer/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Office 4 Light"
  command_topic: "cmnd/sonoff74/POWER"
  state_topic: "tele/sonoff74/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff74/LWT"
  brightness_command_topic: "cmnd/sonoff74/Dimmer"
  brightness_state_topic: "tele/sonoff74/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/sonoff74/CT"
  color_temp_state_topic: "tele/sonoff74/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/sonoff74/Color2"
  rgb_state_topic: "tele/sonoff74/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/sonoff74/Scheme"
  effect_state_topic: "tele/sonoff74/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Office 3 Light"
  command_topic: "cmnd/sonoff73/POWER"
  state_topic: "tele/sonoff73/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff73/LWT"
  brightness_command_topic: "cmnd/sonoff73/Dimmer"
  brightness_state_topic: "tele/sonoff73/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/sonoff73/CT"
  color_temp_state_topic: "tele/sonoff73/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/sonoff73/Color2"
  rgb_state_topic: "tele/sonoff73/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/sonoff73/Scheme"
  effect_state_topic: "tele/sonoff73/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Office 2 Light"
  command_topic: "cmnd/sonoff72/POWER"
  state_topic: "tele/sonoff72/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff72/LWT"
  brightness_command_topic: "cmnd/sonoff72/Dimmer"
  brightness_state_topic: "tele/sonoff72/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/sonoff72/CT"
  color_temp_state_topic: "tele/sonoff72/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/sonoff72/Color2"
  rgb_state_topic: "tele/sonoff72/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/sonoff72/Scheme"
  effect_state_topic: "tele/sonoff72/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Office 1 Light"
  command_topic: "cmnd/sonoff71/POWER"
  state_topic: "tele/sonoff71/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff71/LWT"
  brightness_command_topic: "cmnd/sonoff71/Dimmer"
  brightness_state_topic: "tele/sonoff71/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/sonoff71/CT"
  color_temp_state_topic: "tele/sonoff71/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/sonoff71/Color2"
  rgb_state_topic: "tele/sonoff71/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/sonoff71/Scheme"
  effect_state_topic: "tele/sonoff71/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Reading Light"
  command_topic: "cmnd/sonoff70/POWER"
  state_topic: "tele/sonoff70/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/sonoff70/LWT"
  brightness_command_topic: "cmnd/sonoff70/Dimmer"
  brightness_state_topic: "tele/sonoff70/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  white_value_state_topic: "tele/sonoff70/STATE"
  white_value_command_topic: "cmnd/sonoff70/White"
  white_value_scale: 100
  white_value_template: "{{ value_json.Channel[3] }}"
  rgb_command_topic: "cmnd/sonoff70/Color2"
  rgb_state_topic: "tele/sonoff70/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/sonoff70/Scheme"
  effect_state_topic: "tele/sonoff70/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "Corner Light"
  state_topic: "stat/sonoff20/POWER"
  command_topic: "cmnd/sonoff20/POWER"
  availability_topic: "tele/sonoff20/LWT"
  rgb_state_topic: "stat/sonoff20/COLOR"
  rgb_command_topic: "cmnd/sonoff20/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x0000' | format(red, green, blue) }}"
  brightness_state_topic: "stat/sonoff20/DIMMER"
  brightness_value_template: "{{ value_json.brightness }}"
  brightness_command_topic: "cmnd/sonoff20/DIMMER"
  brightness_scale: 100
  color_temp_command_topic: "cmnd/sonoff20/CT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Desk Light"
  command_topic: "cmnd/tasmota11/POWER"
  state_topic: "stat/tasmota11/POWER"
  rgb_state_topic: "stat/tasmota11/color"
  rgb_command_topic: "cmnd/tasmota11/color"
  brightness_state_topic: "stat/tasmota11/dimmer"
  brightness_command_topic: "cmnd/tasmota11/dimmer"
  brightness_scale: 100
  color_temp_state_topic: "stat/tasmota11/CT"
  color_temp_command_topic: "cmnd/tasmota11/CT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Bed Light"
  state_topic: "stat/sonoff21/POWER"
  command_topic: "cmnd/sonoff21/POWER"
  availability_topic: "tele/sonoff21/LWT"
  rgb_state_topic: "stat/sonoff21/COLOR"
  rgb_command_topic: "cmnd/sonoff21/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x0000' | format(red, green, blue) }}"
  brightness_state_topic: "stat/sonoff21/DIMMER"
  brightness_value_template: "{{ value_json.brightness }}"
  brightness_command_topic: "cmnd/sonoff21/DIMMER"
  brightness_scale: 100
  color_temp_command_topic: "cmnd/sonoff21/CT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Hallway Night Light"
  command_topic: "cmnd/sonoff39/power1"
  state_topic: "stat/sonoff39/POWER1"
  availability_topic: "tele/sonoff39/LWT"
  brightness_state_topic: "stat/sonoff36/dimmer"
  brightness_value_template: "{{ value_json.brightness }}"
  brightness_command_topic: "cmnd/sonoff39/dimmer"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Hall Night Light"
  command_topic: "cmnd/sonoff39/power1"
  state_topic: "stat/sonoff39/POWER1"
  availability_topic: "tele/sonoff39/LWT"
  brightness_state_topic: "stat/sonoff39/dimmer"
  brightness_value_template: "{{ value_json.brightness }}"
  brightness_command_topic: "cmnd/sonoff39/dimmer"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Den Night Light"
  command_topic: "cmnd/sonoff39/power1"
  state_topic: "stat/sonoff39/POWER1"
  availability_topic: "tele/sonoff39/LWT"
  brightness_state_topic: "stat/sonoff39/dimmer"
  brightness_value_template: "{{ value_json.brightness }}"
  brightness_command_topic: "cmnd/sonoff39/dimmer"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Den Nite Light 5"
  command_topic: "cmnd/sonoff80/power2"
  state_topic: "stat/sonoff80/POWER2"
  availability_topic: "tele/sonoff80/LWT"
  brightness_state_topic: "stat/sonoff80/dimmer"
  brightness_value_template: "{{ value_json.brightness }}"
  brightness_command_topic: "cmnd/sonoff80/dimmer"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Mbath Night Light"
  command_topic: "cmnd/sonoff40/power2"
  state_topic: "stat/sonoff40/POWER2"
  availability_topic: "tele/sonoff40/LWT"
  brightness_state_topic: "stat/sonoff40/dimmer"
  brightness_value_template: "{{ value_json.brightness }}"
  brightness_command_topic: "cmnd/sonoff40/dimmer"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: switch
  name: Attic Lights
  entity_id: switch.attic_lights

- platform: switch
  name: TV Accent Lights
  entity_id: switch.tv_accent_lights

- platform: switch
  name: Back Flood Lights
  entity_id: switch.back_flood_lights

- platform: switch
  name: Bedroom Ceiling Light
  entity_id: switch.bedroom_ceiling_light

- platform: switch
  name: Kitchen Ceiling Center
  entity_id: switch.ceiling_center

- platform: switch
  name: Kitchen Ceiling Left
  entity_id: switch.ceiling_left

- platform: switch
  name: Kitchen Ceiling Right
  entity_id: switch.ceiling_right

- platform: switch
  name: Coffee Light
  entity_id: switch.coffee_light

- platform: switch
  name: Cabinet Left
  entity_id: switch.kitchen_cabinet_lights

- platform: switch
  name: Cabinet Right
  entity_id: switch.kitchen_stove_light

- platform: group
  name: Cabinet Lights
  entities:
    - light.cabinet_left
    - light.cabinet_right
    - light.coffee_light

- platform: switch
  name: Desk Back Light
  entity_id: switch.desk_back_light

- platform: switch
  name: Foyer Accent Lights
  entity_id: switch.foyer_accent_lights

- platform: switch
  name: Foyer Light
  entity_id: switch.foyer_light

- platform: switch
  name: Front Flood Lights
  entity_id: switch.front_flood_lights

- platform: switch
  name: Garage Ceiling Lights
  entity_id: switch.garage_ceiling_lights

- platform: switch
  name: Entry Hall Light
  entity_id: switch.hall_light

- platform: switch
  name: Entry Hall Light Switch
  entity_id: switch.hall_switch_1

- platform: group
  name: Entry Hall Lights
  entities:
    - light.entry_hall_light
    - light.entry_hall_light_switch

- platform: switch
  name: Hallway Light
  entity_id: switch.hallway_light

- platform: switch
  name: Den Ceiling Light
  entity_id: switch.living_room_ceiling_light

- platform: switch
  name: Den Lamp
  entity_id: switch.living_room_lamp

- platform: switch
  name: Patio Light
  entity_id: switch.patio_light

- platform: switch
  name: Porch Light
  entity_id: switch.porch_light

- platform: switch
  name: Side Door Light
  entity_id: switch.side_door_light

- platform: switch
  name: Guest Ceiling Light
  entity_id: switch.guest_ceiling_light

- platform: switch
  name: Table Light
  entity_id: switch.table_light

- platform: switch
  name: Salt Light
  entity_id: switch.salt_light

- platform: switch
  name: Sink Light
  entity_id: switch.kitchen_sink_light

- platform: switch
  name: Laundry Light
  entity_id: switch.laundry_light

- platform: switch
  name: Patio Accent Lights
  entity_id: switch.patio_accent_lights_switch

- platform: switch
  name: Bathroom Ceiling
  entity_id: switch.bathroom_ceiling

- platform: switch
  name: Bathroom Mirror
  entity_id: switch.bathroom_mirror_light

- platform: switch
  name: Ensuite Ceiling Light
  entity_id: switch.ensuite_ceiling

- platform: group
  name: Office Ceiling
  entities:
    - light.office_1_light
    - light.office_2_light
    - light.office_3_light
    - light.office_4_light
    - light.officedimmer

- platform: group
  name: Office Lamps
  entities:
    - light.corner_light
    - light.bed_light
    - light.desk_light

- platform: group
  name: Bedroom Lamps
  entities:
    - light.darrens_light
    - light.donnas_light

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_ceiling
    - light.bathroom_mirror

- platform: mqtt
  name: "Side Display"
  command_topic: "cmnd/sonoff59/power"
  state_topic: "stat/sonoff59/POWER"
  availability_topic: "tele/sonoff59/LWT"
  qos: 1
  payload_available: "Online"
  payload_not_available: "Offline"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
