---
# # notify#  /config/includes/notify.yaml
# #######################################################
- name: notify_all
  platform: group
  services:
    - service: ios_donnas_iphone
    - service: darren

# pushbullet
- platform: pushbullet
  name: Darren
  api_key: !secret pushbullet_api
  
# html5
- platform: html5
  name: Darren Pixel 2XL
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email
