---
# /config/packages/coffeemaker.yaml
# credits to Thomas Loven for coffee package
#########################################################
homeassistant:
  customize:
    package.node_anchors:
      coffee_switch: &cfe_switch switch.coffee_maker
      common: &common
        package: coffeemaker

    input_datetime.cfe_on:
      <<: *common
      friendly_name: Time
    input_number.cfe_off:
      <<: *common
      friendly_name: Timer (mins)
    input_boolean.cfe_on:
      <<: *common
      friendly_name: Morning Coffee
      icon: mdi:weather-sunset-up
    input_boolean.cfe_off:
      <<: *common
      friendly_name: Automatic shut off
      icon: mdi:stop-circle
    script.cfe_off:
      <<: *common
    automation.coffee_timer_on:
      <<: *common
    automation.coffee_auto_off:
      <<: *common

input_datetime:
  cfe_on:
    has_date: false
    has_time: true
    initial: "05:00"
input_number:
  cfe_off:
    initial: 15
    min: 5
    max: 60
    step: 5
input_boolean:
  cfe_on:
    initial: false
  cfe_off:
    initial: true

script:
  cfe_off:
    sequence:
      - delay: 00:{{ states('input_number.cfe_off') | int}}:00
      - service: homeassistant.turn_off
        data:
          entity_id: *cfe_switch
      - service: notify.darren
        data_template:
          message: "Coffee maker has turned off. The ({{ states('input_number.cfe_off') | int }} minute timer has expired)"
      - service: script.browser_close_popup

  coffee_time_popup:
    sequence:
      - service: browser_mod.command
        data:
          command: close-popup
      - service: browser_mod.command
        data:
          command: popup
          title: " "
          style:
            background: linear-gradient(rgb(230,230,230), 30%, rgba(0,0,0,0.95))
            border-radius: 22px
            border: solid 3px DimGray
            font-size: 1.7em
            font-weight: bold
            "--paper-slider-knob-color": '#F2F2F2'
            "--paper-slider-knob-start-color": '#f5f5f5'
            "--paper-slider-pin-color": '#f5f5f5'
            "--paper-slider-active-color": '#F2F2F2'
            "--primary-color": rgba(245, 245, 245,0.45)
            "--primary-text-color": rgba(245, 245, 245,0.6)
            text-shadow: "0 1px 0 #CCCCCC, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0,0,0,.1), 0 0 5px rgba(0,0,0,.1), 0 1px 3px rgba(0,0,0,.3), 0 3px 5px rgba(0,0,0,.2), 0 5px 10px rgba(0,0,0,.25), 0 10px 10px rgba(0,0,0,.2), 0 20px 20px rgba(0,0,0,.15)"
            width: 375px
            height: 753px
            padding: 4px 0px 0px 0px
            box-sizing: border-box
            margin: 0
          card:
            type: custom:card-modder
            style:
              background-image: url("/local/images-lovelace/backgroundz/coffee44444.png")
              background-repeat: no-repeat
              background-size: 100% 100%
              "--primary-color": rgba(245, 245, 245,0.4)
            card:
              type: entities
              show_header_toggle: false
              entities:
                - type: custom:dummy-entity-row
                  entity: sun.sun
                  icon: mdi:this-icon-does-not-exist
                  name: " "
                - type: custom:dummy-entity-row
                  entity: sun.sun
                  icon: mdi:this-icon-does-not-exist
                  name: " "
                - type: custom:dummy-entity-row
                  entity: sun.sun
                  icon: mdi:this-icon-does-not-exist
                  name: " "
                - type: custom:dummy-entity-row
                  entity: sun.sun
                  icon: mdi:this-icon-does-not-exist
                  name: " "
                - type: custom:dummy-entity-row
                  entity: sun.sun
                  icon: mdi:this-icon-does-not-exist
                  name: " "
                - switch.coffee_maker
                - input_boolean.cfe_on
                - entity: input_datetime.cfe_on
                  name: "Start Time"
                - input_boolean.cfe_off
                - entity: input_number.cfe_off
                  name: "Timer"
                - type: custom:bignumber-card
                  entity: sensor.time_12_hour
                  scale: 62px

automation:
  - alias: Coffee - Timer On
    initial_state: True
    trigger:
      - platform: template
        value_template: >
          {{ states('sensor.time') == states('input_datetime.cfe_on')[:5] }}
    condition:
      condition: state
      entity_id: input_boolean.cfe_on
      state: 'on'
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.cfe_on
      - service: homeassistant.turn_on
        data:
          entity_id: *cfe_switch
      - service: notify.darren
        data_template:
          message: "Coffee maker is on and will turn off in ({{ states('input_number.cfe_off') | int }} minutes)"

  - alias: Coffee - Auto Off
    initial_state: True
    trigger:
      - platform: state
        entity_id: *cfe_switch
        to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.cfe_off
      state: 'on'
    action:
      - service: script.cfe_off
